spring.application.name=poc-kc-composite-customer-api

server.port=8191

# Keycloak Config

# issuer
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/ejemplo-realm-dev

# Client ID
jwt.auth.converter.resource-id=poc-kc-customer-api

# preferred_username del JWT
jwt.auth.converter.principal-attribute=preferred_username

logging.level.org.keycloak=DEBUG