spring.application.name=poc-kc-composite-billing-api

server.port=8190

# Keycloak Config

# issuer
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/bp4-realm-dev

# Client ID
jwt.auth.converter.resource-id=poc-kc-billing-api

# preferred_username del JWT
jwt.auth.converter.principal-attribute=preferred_username

logging.level.org.keycloak=DEBUG